version: "3.8"

services:
    repo_command_server:
        build: .
        container_name: repo-command
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - APP_ID=${APP_ID}
            - PRIVATE_KEY=${PRIVATE_KEY}
            - WEBHOOK_SECRET=${WEBHOOK_SECRET}
            - WEBHOOK_PROXY_URL=${WEBHOOK_PROXY_URL}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - LOG_LEVEL=info
        env_file:
            - .env
        ports:
            - "3005:3000"
        volumes:
            # Mount config file if you want to modify it without rebuilding
            - ./config:/app/config:ro
